package com.selfanalyst.desktop.service;

import com.selfanalyst.desktop.store.ChatSessionStore;

import java.time.Duration;
import java.util.ArrayList;
import java.util.List;

/**
 * Produces a one-line session summary used as the search "content proxy"
 * (SPEC-CSP-DEC-009/-010). Generated by the LLM from session content only,
 * with a deterministic fallback when the LLM is unavailable / budget-blocked /
 * fails (SPEC-CSP-API-011b). The summary input is the session's own
 * messages/title — never config secrets (SPEC-CSP-API-011d / DEC-007).
 * <p>
 * Reuses {@link SummaryPromptService.SummaryTextClient} (do not redefine).
 */
public class ChatSummaryService {

    /** Cap on how many trailing messages feed the prompt, to bound tokens. */
    private static final int MAX_PROMPT_MESSAGES = 20;
    /** Per-message trim length inside the prompt. */
    private static final int MSG_TRIM = 200;
    /** Final summary length cap (~one line). */
    private static final int SUMMARY_LEN = 80;
    /** Number of user-message snippets used by the deterministic fallback. */
    private static final int FALLBACK_SNIPPETS = 3;

    /**
     * Summarize a session in one line. With a null {@code client}, or on any
     * blank/failed LLM result, returns {@link #deterministicFallback}.
     */
    public String summarize(ChatSessionStore.Session session,
                            SummaryPromptService.SummaryTextClient client) {
        if (client == null) {
            return deterministicFallback(session);
        }
        try {
            String prompt = buildPrompt(session);
            String response = client.complete(prompt, Duration.ofSeconds(5));
            if (response == null || response.isBlank()) {
                return deterministicFallback(session);
            }
            String normalized = normalize(response);
            return normalized.isBlank() ? deterministicFallback(session) : normalized;
        } catch (Exception e) {
            return deterministicFallback(session);
        }
    }

    // ── Prompt ───────────────────────────────────────────────────

    /**
     * Build the prompt from session content only (title + last ~20 messages,
     * each trimmed). No config/secret values are ever referenced
     * (SPEC-CSP-API-011d / DEC-007 / DEC-010).
     */
    private static String buildPrompt(ChatSessionStore.Session session) {
        StringBuilder body = new StringBuilder();
        if (session.title != null && !session.title.isBlank()) {
            body.append("会话标题：").append(session.title.strip()).append('\n');
        }
        List<ChatSessionStore.Message> messages =
                session.messages != null ? session.messages : List.of();
        int from = Math.max(0, messages.size() - MAX_PROMPT_MESSAGES);
        for (int i = from; i < messages.size(); i++) {
            ChatSessionStore.Message m = messages.get(i);
            if (m.content == null || m.content.isBlank()) continue;
            String role = "assistant".equals(m.role) ? "助手" : "system".equals(m.role) ? "系统" : "用户";
            body.append(role).append("：").append(trim(m.content, MSG_TRIM)).append('\n');
        }
        return """
                你是 SelfAnalyst，请用一句中文概括下面这段对话聊了什么，便于以后按内容检索会话。
                只输出概括本身，不要前缀、引号、代码块或多余说明，不超过 40 字。

                对话内容：
                %s
                """.formatted(body.toString().strip());
    }

    // ── Fallback ─────────────────────────────────────────────────

    /**
     * Deterministic summary: join the leading text of the first ≤3 user
     * messages (" / "), trimmed to ~80 chars; fall back to the title. Never
     * empty (SPEC-CSP-API-011b, TST-015).
     */
    static String deterministicFallback(ChatSessionStore.Session s) {
        List<String> snippets = new ArrayList<>();
        if (s != null && s.messages != null) {
            for (ChatSessionStore.Message m : s.messages) {
                if (!"user".equals(m.role) || m.content == null || m.content.isBlank()) continue;
                snippets.add(trim(m.content, 40));
                if (snippets.size() >= FALLBACK_SNIPPETS) break;
            }
        }
        String joined = String.join(" / ", snippets).strip();
        if (!joined.isBlank()) {
            return trim(joined, SUMMARY_LEN);
        }
        if (s != null && s.title != null && !s.title.isBlank()) {
            return trim(s.title.strip(), SUMMARY_LEN);
        }
        return "新会话";
    }

    // ── Helpers ──────────────────────────────────────────────────

    /** Collapse to a single line, strip fences/quotes, trim to ~80 chars. */
    private static String normalize(String raw) {
        String line = raw.strip();
        // Drop leading/trailing code fences and stray quotes.
        line = line.replace("```", "").strip();
        if (line.length() >= 2
                && (line.charAt(0) == '"' || line.charAt(0) == '“' || line.charAt(0) == '「')) {
            line = line.substring(1);
        }
        if (!line.isEmpty()) {
            char last = line.charAt(line.length() - 1);
            if (last == '"' || last == '”' || last == '」') {
                line = line.substring(0, line.length() - 1);
            }
        }
        // First non-blank line only.
        int nl = line.indexOf('\n');
        if (nl >= 0) line = line.substring(0, nl);
        return trim(line.strip(), SUMMARY_LEN);
    }

    private static String trim(String text, int max) {
        String t = text.strip();
        return t.length() > max ? t.substring(0, max) : t;
    }
}
